.TH topost 1 "version 2.0"
.SH NAME
topost \- Display client for an OSS, sorted by bandwith usage
.SH SYNOPSIS
.B topost
.IR 
.SH DESCRIPTION
.B topost
stat osts counters and display client sorted by read/write/iops usage
.bp
.SH OPTIONS
.TP
.BR \-n
number of client to print in the output
(10 is the default value)
.TP
.BR \-h
Print help
.TP
.BR \-v
Print version
.bp
.BR 
.SH AUTHOR
Quentin Bouyer quentin.bouyer@gmail.com
